### ISSUE TITLE
Cant create RMAs for products in a phantom BoM.

### ISSUE THREAD

**Issue by Alex-Vining** [OCA/rma#307]
## Module
rma

## Describe the bug
Whenever you try to confirm a rma with a product that has a ```mrp.bom``` with the type of 'kit' an error is raised. I think this is because phantom BoMs will break out 1 ```stock.move``` record into multiple ```stock.move``` records when they are confirmed.

## To Reproduce
**Affected versions**: Odoo 15.0 

1. Install mrp & rma
2. Setup a product with a phantom BoM with at least 2 lines
3. Create an RMA with the same product
4. Click the "Confirm" button

**Additional context**
Here is the stack trace for the error:
```
2022-09-19 13:08:15,166 634920 ERROR db odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "odoo/addons/web/controllers/main.py", line 1347, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "odoo/addons/web/controllers/main.py", line 1335, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "odoo/api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "odoo/api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "3rd-party-addons/rma/models/rma.py", line 665, in action_confirm
    self.write({"reception_move_id": reception_move.id, "state": "confirmed"})
  File "odoo/fields.py", line 4061, in __get__
    raise ValueError("Expected singleton: %s" % record)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Expected singleton: stock.move(557383, 557384, 557385, 557386, 557387, 557388, 557389, 557390, 557391)
2022-09-19 13:08:15,174 634920 INFO db werkzeug: 127.0.0.1 - - [19/Sep/2022 13:08:15] "POST /web/dataset/call_button HTTP/1.1" 200 - 1211 1.493 208.678
```

**Comment by pedrobaeza** [comment]
This module should be migrated: https://github.com/OCA/rma/tree/14.0/rma_sale_mrp
