### ISSUE TITLE
Can't Install 8.0 branch on Odoo 8.0

### ISSUE THREAD

**Issue by BGEray** [OCA/rma#78]
I can't Install 8.0 branch on Odoo 8.0，an error occured below：
2016-03-17 22:38:38,901 8312 ERROR new2 openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "D:\Odoo\odoo-9.0c-20160107\openerp\http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\Odoo\odoo-9.0c-20160107\openerp\http.py", line 685, in dispatch
    result = self._call_function(*_self.params)
  File "D:\Odoo\odoo-9.0c-20160107\openerp\http.py", line 317, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "D:\Odoo\odoo-9.0c-20160107\openerp\service\model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "D:\Odoo\odoo-9.0c-20160107\openerp\http.py", line 310, in checked_call
    result = self.endpoint(_a, *_kw)
  File "D:\Odoo\odoo-9.0c-20160107\openerp\http.py", line 964, in __call__
    return self.method(_args, *_kw)
  File "D:\Odoo\odoo-9.0c-20160107\openerp\http.py", line 514, in response_wrap
    response = f(_args, *_kw)
  File "D:\Odoo\odoo-9.0c-20160107\openerp\addons\web\controllers\main.py", line 896, in call_button
    action = self._call_kw(model, method, args, {})
  File "D:\Odoo\odoo-9.0c-20160107\openerp\addons\web\controllers\main.py", line 884, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "D:\Odoo\odoo-9.0c-20160107\openerp\api.py", line 238, in wrapper
    return old_api(self, _args, *_kwargs)
  File "D:\Odoo\odoo-9.0c-20160107\openerp\addons\base\module\module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "D:\Odoo\odoo-9.0c-20160107\openerp\api.py", line 238, in wrapper
    return old_api(self, _args, *_kwargs)
  File "D:\Odoo\odoo-9.0c-20160107\openerp\addons\base\module\module.py", line 533, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "D:\Odoo\odoo-9.0c-20160107\openerp\modules\registry.py", line 385, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "D:\Odoo\odoo-9.0c-20160107\openerp\modules\loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "D:\Odoo\odoo-9.0c-20160107\openerp\modules\loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "D:\Odoo\odoo-9.0c-20160107\openerp\modules\loading.py", line 136, in load_module_graph
    registry.setup_models(cr, partial=True)
  File "D:\Odoo\odoo-9.0c-20160107\openerp\modules\registry.py", line 199, in setup_models
    model._setup_fields(cr, SUPERUSER_ID)
  File "D:\Odoo\odoo-9.0c-20160107\openerp\api.py", line 238, in wrapper
    return old_api(self, _args, *_kwargs)
  File "D:\Odoo\odoo-9.0c-20160107\openerp\api.py", line 342, in old_api
    result = method(recs, _args, *_kwargs)
  File "D:\Odoo\odoo-9.0c-20160107\openerp\models.py", line 3045, in _setup_fields
    field.setup_full(self)
  File "D:\Odoo\odoo-9.0c-20160107\openerp\fields.py", line 476, in setup_full
    self._setup_regular_full(model)
  File "D:\Odoo\odoo-9.0c-20160107\openerp\fields.py", line 1847, in _setup_regular_full
    invf = comodel._fields[self.inverse_name]
KeyError: 'claim_return_id'

**Comment by osvalr** [comment]
Hi @BGEray, can you specify the details about how to reproduce it? HINT: you can use [this template](https://github.com/OCA/rma/issues/new?body=module:%20What module?%0Aversion:%20 What branch?%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Expected%20behavior**)

**Comment by BGEray** [comment]
module:crm_claim_ext
version:8.0
just click install button,then an error occured:
Traceback (most recent call last):
  File "D:\Odoo\odoo-8.0-20151109\openerp\http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\Odoo\odoo-8.0-20151109\openerp\http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "D:\Odoo\odoo-8.0-20151109\openerp\http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "D:\Odoo\odoo-8.0-20151109\openerp\service\model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "D:\Odoo\odoo-8.0-20151109\openerp\http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "D:\Odoo\odoo-8.0-20151109\openerp\http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "D:\Odoo\odoo-8.0-20151109\openerp\http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "D:\Odoo\odoo-8.0-20151109\openerp\addons\web\controllers\main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "D:\Odoo\odoo-8.0-20151109\openerp\addons\web\controllers\main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "D:\Odoo\odoo-8.0-20151109\openerp\api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "D:\Odoo\odoo-8.0-20151109\openerp\addons\base\module\module.py", line 447, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "D:\Odoo\odoo-8.0-20151109\openerp\api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "D:\Odoo\odoo-8.0-20151109\openerp\addons\base\module\module.py", line 495, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "D:\Odoo\odoo-8.0-20151109\openerp\modules\registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "D:\Odoo\odoo-8.0-20151109\openerp\modules\loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "D:\Odoo\odoo-8.0-20151109\openerp\modules\loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "D:\Odoo\odoo-8.0-20151109\openerp\modules\loading.py", line 156, in load_module_graph
    registry.setup_models(cr, partial=True)
  File "D:\Odoo\odoo-8.0-20151109\openerp\modules\registry.py", line 194, in setup_models
    model._setup_fields(cr, SUPERUSER_ID)
  File "D:\Odoo\odoo-8.0-20151109\openerp\api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "D:\Odoo\odoo-8.0-20151109\openerp\api.py", line 345, in old_api
    result = method(recs, _args, *_kwargs)
  File "D:\Odoo\odoo-8.0-20151109\openerp\models.py", line 3005, in _setup_fields
    field.setup(self.env)
  File "D:\Odoo\odoo-8.0-20151109\openerp\fields.py", line 455, in setup
    self._setup_regular(env)
  File "D:\Odoo\odoo-8.0-20151109\openerp\fields.py", line 1753, in _setup_regular
    invf = comodel._fields[self.inverse_name]
KeyError: 'claim_return_id'
